# Generated by Django 4.2.11 on 2024-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=30)),
                ("second_name", models.CharField(max_length=30)),
                ("avatar", models.CharField(max_length=255)),
                ("level", models.IntegerField(default=1)),
            ],
        ),
    ]
