# Generated by Django 4.2.11 on 2024-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
